//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdfb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sdfb.Properties.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to continue? Y/N: .
        /// </summary>
        internal static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: .
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the file: .
        /// </summary>
        internal static string errorread {
            get {
                return ResourceManager.GetString("errorread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist: .
        /// </summary>
        internal static string fdne {
            get {
                return ResourceManager.GetString("fdne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the full path including the file name:.
        /// </summary>
        internal static string fileprompt {
            get {
                return ResourceManager.GetString("fileprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter scrambled words manually (separated by commas if multiple):.
        /// </summary>
        internal static string manualentry {
            get {
                return ResourceManager.GetString("manualentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Unscrambled words manually (separated by commas).
        /// </summary>
        internal static string manualentrysol {
            get {
                return ResourceManager.GetString("manualentrysol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered option was not recognized..
        /// </summary>
        internal static string notreccognizedexeption {
            get {
                return ResourceManager.GetString("notreccognizedexeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scramble word matching.
        /// </summary>
        internal static string nswm {
            get {
                return ResourceManager.GetString("nswm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter scrambled word(s) manually or as a file: F - file / M - manual. Press &quot;L&quot; to change language to french.
        /// </summary>
        internal static string startingprompt {
            get {
                return ResourceManager.GetString("startingprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the unscrambled version of : .
        /// </summary>
        internal static string unscrambledversionof {
            get {
                return ResourceManager.GetString("unscrambledversionof", resourceCulture);
            }
        }
    }
}
